### PR TITLE
Documented options in readme and script

### PR DESCRIPTION
**Pull request by MSLaaf**
Does this do the job? If so, I'll create pull reqs for the other branches...

### CODE REVIEW

**Comment by morrownr** [comment]
I'm going to merge this and do some testing with this 8821au driver this afternoon to make sure the law of unintended consequences doesn't get the best of us. If it test good on this end, do you want to make Pull requests for the other 4 drivers or should I use meld and move the improvements into the other drivers? Your call.

Also, if you see any other improvements in any of the scripts, please feel free to work on them. That would give me more time to concentrate on some other issues I am working on.

Thanks, Nick

**Comment by MSLaaf** [comment]
Nick,

Thank you. I think it's quicker with meld, so I'm ok with that. I'll keep
an eye out on other issues. I have a setup where I'm building a custom
image for a Pi 4 which uses these drivers.

The other issue - maybe a different thread - is the issue with IBSS not
working at all with the realtek drivers. I got the Mediatek USB adapter
from Rokland - and it works like a charm. I am under a time crunch, so I
currently have not much time to work on those drivers - to fix them... But
I am thinking that I should at least make a change to them to make them
either not report IBSS as an option (which imho is the most correct - or
reject the IBSS mode change with an error. Whether it would be just in our
environment or in the main tree doesn't matter too much to me. I just need
to make sure that I discover the right functionality for my testing...

I wonder whether this policy change from Windows 10:
https://www.connectify.me/blog/features/what-is-wi-fi-direct/ rolled into
Realtek's Linux drivers too...

Kind regards,

Maurice


Kind regards,

Maurice

**Comment by morrownr** [comment]
Maurice,

Thank you for the work. I will use meld to propagate as required.

Since you are working with a Pi 4, let me suggest a possible improvement to install-driver.sh. Step 8 currently tells users that are compiling on RasPi hardware to run one of two prep scripts. It would be nice, for the sake of simplicity, to integrate those scripts into install-driver.sh. Do you see a way to do it that makes it idiot-proof? I'm seeing over 3,000 hits per week on these drivers (all 5) and the experience level of those using these drivers varies greatly so when I say "idiot-proof" I really mean it.

Concerning the IBSS issue. It would be best if you start a new issue for this so we can keep things organized. Right now I am neck deep working the WPA3 issue. You are welcome to try to fix the IBSS problem or make a quick change so that they do not report the capability. Welcome to the frustrating world of Realtek USB WiFi drivers.

Regards,

Nick

**Comment by MSLaaf** [comment]
Nick,

I will make some smart changes to the build script so it checks uname what
architecture it is and then automatically sets the right flags... Maybe
make, maybe just bash. But it makes sense, to get it more KISS for the
raspi users...

while that is more the domain of autoconf  - I think that would be beyond
the scope of most basic users... or would you rather like to see an
autoconf setup?

Maurice

**Comment by morrownr** [comment]
Maurice,

Can I suggest that you use just bash, at least for a first attempt? These drivers come with a Makefile, dkms.conf and various other configuration files. What I have learned is that if we make the minimum changes to those files then it is easier to incorporate a new version of the driver when available. So, as long as it makes sense, let's try to use bash files.

Nick

**Comment by MSLaaf** [comment]
Nick.

Ok. I have - not yet tested - a way to do it - and it likely will work even
using buildroot (done a lot with it in a previous career) - I do not have
access to a 32 bit Linux anymore though - and no time to set it up...

I will try to do testing on a x86_64 linux,. a 32 and 64 bit Pi image.

Basically, it simplifies building it on a pi to just run install-driver.sh
;-)

Maurice

**Comment by morrownr** [comment]
Maurice,

I have access to 32 bit Linux and even 32 bit x86 systems with Linux. My little lab is not that big but I can test a lot of situations. You get it to me and I will test it.

If I recall correctly, you had a problem you needed to solve in a limited amount of time. I don't remember that you spelled out exactly what you were doing but if I can help, let me know.

Oh, and can I get you to open an issue for future correspondence as digging into a closed pull request is sort of a pain.

Nick

**Pull request merged**
